# -*- coding: utf-8 -*-
"""new model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sLFS0SbED5SaWieGNJBGTfVLj6q6tdjp

แบ่งข้อมูล train test
"""

import pandas as pd
import numpy as np
import re
import os
import zipfile
from sklearn.model_selection import train_test_split
from google.colab import files

# ==========================================
# 1. โหลดข้อมูล (แก้ให้รองรับทั้ง xlsx และ csv)
# ==========================================
file_name = '/content/drive/MyDrive/Web Orchid/PROJECT_DATA.xlsx' # หรือชื่อไฟล์ .xlsx ของคุณ

print(f"📂 กำลังอ่านไฟล์: {file_name} ...")
try:
    if file_name.endswith('.csv'):
        df = pd.read_csv(file_name)
    else:
        df = pd.read_excel(file_name)
    print("✅ อ่านไฟล์สำเร็จ!")
except Exception as e:
    print(f"❌ อ่านไฟล์ไม่สำเร็จ: {e}")
    df = pd.DataFrame()

# ==========================================
# 2. ฟังก์ชันคำนวณ Feature (Peak, Area, Width)
# ==========================================
def get_species_name(col_name):
    m = re.match(r"^([A-Za-z]+)", str(col_name))
    if m: return m.group(1)
    return "Unknown"

def extract_peak_features(t, f):
    mask = ~np.isnan(t) & ~np.isnan(f)
    t, f = np.asarray(t[mask]), np.asarray(f[mask])

    if len(t) < 3: return np.nan, np.nan, np.nan, np.nan

    sort_idx = np.argsort(t)
    t, f = t[sort_idx], f[sort_idx]

    peak_idx = np.argmax(f)
    F_peak = float(f[peak_idx])
    T_peak = float(t[peak_idx])

    if hasattr(np, 'trapezoid'): area = float(np.trapezoid(f, x=t))
    else: area = float(np.trapz(f, t))

    half = F_peak / 2.0
    above_half = np.where(f >= half)[0]
    if len(above_half) >= 2:
        width = float(t[above_half[-1]] - t[above_half[0]])
    else: width = np.nan

    return T_peak, F_peak, width, area

# ==========================================
# 3. วนลูปสกัด Feature จากทุกคอลัมน์
# ==========================================
if not df.empty:
    columns = df.columns.tolist()
    data_rows = []
    processed_pairs = set()

    print("⚙️ กำลังคำนวณ Feature ทั้งหมด...")
    for col in columns:
        m = re.match(r"^(.*)T(\d+)$", str(col))
        if m:
            prefix, num = m.group(1), m.group(2)
            f_col = f"{prefix}F{num}"

            if f_col in columns and col not in processed_pairs:
                processed_pairs.add(col)

                t_vals = pd.to_numeric(df[col], errors='coerce').values
                f_vals = pd.to_numeric(df[f_col], errors='coerce').values

                # คำนวณทันที
                T_peak, F_peak, width, area = extract_peak_features(t_vals, f_vals)
                species = get_species_name(col)

                if not np.isnan(T_peak):
                    data_rows.append({
                        "species": species,
                        "T_peak": T_peak,
                        "F_peak": F_peak,
                        "Width_FWHM": width,
                        "Area": area
                    })

    full_df = pd.DataFrame(data_rows)
    print(f"✅ สกัดข้อมูลได้: {len(full_df)} ตัวอย่าง")

    # ==========================================
    # 4. Clean Data & Split (ตามเงื่อนไขเดิม)
    # ==========================================
    # ลบแถวที่มีค่าว่างทิ้ง (ไม่เติม Median)
    full_df.dropna(inplace=True)
    print(f"✅ ข้อมูลพร้อมใช้หลัง Clean: {len(full_df)} ตัวอย่าง")

    try:
        # แบ่ง 90% (Train+Val) : 10% (Test)
        train_val_df, test_df = train_test_split(full_df, test_size=0.10, stratify=full_df['species'], random_state=42)

        # แบ่ง 90% นั้นเป็น Train และ Validation
        train_final_df, validation_df = train_test_split(train_val_df, test_size=1/9, stratify=train_val_df['species'], random_state=42)

        # บันทึกไฟล์รวม
        output_filename = 'orchid_dataset_ready.xlsx'
        with pd.ExcelWriter(output_filename) as writer:
            train_final_df.to_excel(writer, sheet_name='Train', index=False)
            validation_df.to_excel(writer, sheet_name='Validation', index=False)
            test_df.to_excel(writer, sheet_name='Test', index=False)
        print(f"💾 บันทึกไฟล์หลัก: {output_filename}")

        # ==========================================
        # 5. สร้าง Blind Test 4 ชุด (ไฟล์ที่มี Feature แล้ว)
        # ==========================================
        print("📦 กำลังสร้างไฟล์ Blind Test...")
        test_shuffled = test_df.sample(frac=1, random_state=99)
        chunks = np.array_split(test_shuffled, 4)

        zip_filename = 'blind_tests_features.zip'
        with zipfile.ZipFile(zip_filename, 'w') as zipf:
            for i, chunk in enumerate(chunks):
                # ไฟล์โจทย์ (ลบเฉลย species ออก แต่เหลือ T_peak, etc.)
                q_name = f'blind_test_set_{i+1}_question.xlsx'
                chunk.drop(columns=['species']).to_excel(q_name, index=False)
                zipf.write(q_name)
                os.remove(q_name)

                # ไฟล์เฉลย (มีครบ)
                a_name = f'blind_test_set_{i+1}_answer.xlsx'
                chunk.to_excel(a_name, index=False)
                zipf.write(a_name)
                os.remove(a_name)

        files.download(output_filename)
        files.download(zip_filename)

    except ValueError as ve:
        print(f"❌ Error แบ่งข้อมูล: {ve}")
else:
    print("⚠️ ไม่พบข้อมูล")

import pandas as pd
import numpy as np
import joblib
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report

# ==========================================
# 1. โหลดข้อมูล
# ==========================================
dataset_file = '/content/drive/MyDrive/Web Orchid/orchid_dataset_ready_l.xlsx'

print(f"📂 กำลังโหลดข้อมูลจาก {dataset_file} ...")
try:
    train_df = pd.read_excel(dataset_file, sheet_name='Train')
    val_df = pd.read_excel(dataset_file, sheet_name='Validation')

    # Clean Data
    feature_cols = ["T_peak", "F_peak", "Width_FWHM", "Area"]
    train_df.dropna(subset=feature_cols, inplace=True)
    val_df.dropna(subset=feature_cols, inplace=True)

    X_train = train_df[feature_cols]
    y_train = train_df["species"]
    X_val = val_df[feature_cols]
    y_val = val_df["species"]

    # Encode Label
    le = LabelEncoder()
    y_train_encoded = le.fit_transform(y_train)
    y_val_encoded = le.transform(y_val)

    # ==========================================
    # 2. Grid Search (ปรับจูนเพื่อแก้ Overfitting)
    # ==========================================
    print("\n🧠 กำลังค้นหา Decision Tree ที่สมดุลที่สุด...")

    param_grid = {
        'max_depth': [3, 4, 5, 6, 7, 8],
        'min_samples_leaf': [3, 4, 5, 6],
        'min_samples_split': [5, 10, 15],
        'criterion': ['gini', 'entropy'],
        'ccp_alpha': [0.0, 0.01, 0.02]
    }

    grid = GridSearchCV(DecisionTreeClassifier(random_state=42), param_grid, cv=5, scoring='accuracy')
    grid.fit(X_train, y_train_encoded)

    best_model = grid.best_estimator_

    print(f"✅ เจอโมเดลที่ดีที่สุดแล้ว!")
    print(f"   - Best Params: {grid.best_params_}")
    print(f"   - Training Score (CV): {grid.best_score_:.2%}")

    # ==========================================
    # 3. วัดผลและบันทึก
    # ==========================================
    # วัดผลกับ Validation Set
    val_preds = best_model.predict(X_val)
    val_acc = accuracy_score(y_val_encoded, val_preds)

    print("-" * 30)
    print(f"📊 Validation Accuracy: {val_acc:.2%}")
    print("-" * 30)

    # ⚠️ แก้ไขจุดที่ Error: เพิ่ม labels=... เพื่อบังคับให้แสดงครบทุก Class
    all_labels = np.arange(len(le.classes_))
    print(classification_report(
        y_val_encoded,
        val_preds,
        labels=all_labels,          # บังคับให้ดูครบทุก Index
        target_names=le.classes_,   # ชื่อสายพันธุ์ครบ 13 ชื่อ
        zero_division=0             # ถ้าพันธุ์ไหนไม่มีให้ใส่ 0 ไม่ต้อง Error
    ))

    # บันทึกโมเดล
    model_filename = "orchid_model_final.pkl"
    joblib.dump({
        "model": best_model,
        "label_encoder": le,
        "feature_columns": feature_cols
    }, model_filename)

    print(f"\n💾 บันทึกโมเดลแล้ว: {model_filename}")


except Exception as e:
    print(f"❌ Error: {e}")